// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperBoard.DomainModels;

namespace SuperBoard.DomainModels.Migrations
{
    [DbContext(typeof(SuperBoardContext))]
    partial class SuperBoardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SuperBoard.DomainModels.Board", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("SuperBoard.DomainModels.Issue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Description");

                    b.Property<DateTime>("EndDate");

                    b.Property<long?>("ListId");

                    b.Property<string>("Name");

                    b.Property<int>("Position");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("SuperBoard.DomainModels.List", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("BoardId");

                    b.Property<string>("Name");

                    b.Property<int>("Position");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("SuperBoard.DomainModels.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("IssueId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SuperBoard.DomainModels.Issue", b =>
                {
                    b.HasOne("SuperBoard.DomainModels.List", "List")
                        .WithMany()
                        .HasForeignKey("ListId");
                });

            modelBuilder.Entity("SuperBoard.DomainModels.List", b =>
                {
                    b.HasOne("SuperBoard.DomainModels.Board")
                        .WithMany("Lists")
                        .HasForeignKey("BoardId");
                });

            modelBuilder.Entity("SuperBoard.DomainModels.Tag", b =>
                {
                    b.HasOne("SuperBoard.DomainModels.Issue")
                        .WithMany("Tags")
                        .HasForeignKey("IssueId");
                });
#pragma warning restore 612, 618
        }
    }
}
